services:
    sonata.admin.livebroadcast:
        class: Martin1982\LiveBroadcastSonataAdminBundle\Admin\LiveBroadcastAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Live Broadcasts"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\LiveBroadcast
            - ~
        calls:
            - [ setTranslationDomain, [LiveBroadcastSonataAdminBundle]]
            - [ setThumbnailPath, ["%livebroadcast.thumbnail.web_path%"]]

    sonata.admin.channel:
        class: Martin1982\LiveBroadcastSonataAdminBundle\Admin\ChannelAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Channels"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\Channel\AbstractChannel
            - LiveBroadcastSonataAdminBundle:CRUD
        calls:
            - [setSubclassConfigs, ["%livebroadcast.config%"]]
            - [setConfiguredSubclasses, [ { "Twitch": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelTwitch, "Facebook": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelFacebook, "YouTube": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelYouTube } ] ]

    sonata.admin.streaminput:
        class: Martin1982\LiveBroadcastSonataAdminBundle\Admin\InputAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Inputs"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\Media\AbstractMedia
            - ~
        calls:
            - [setSubClasses, [ { "File": Martin1982\LiveBroadcastBundle\Entity\Media\MediaFile, "URL": Martin1982\LiveBroadcastBundle\Entity\Media\MediaUrl, "RTMP": Martin1982\LiveBroadcastBundle\Entity\Media\MediaRtmp } ] ]

    sonata.block.service.youtubeauth:
        class: Martin1982\LiveBroadcastSonataAdminBundle\Admin\Block\YouTubeBlockService
        arguments:
            - "@twig.loader"
            - "@live.broadcast.channel_api.client.google"
            - "@request_stack"
        tags:
            - { name: sonata.block }

    sonata.block.service.facebookauth:
        class: Martin1982\LiveBroadcastSonataAdminBundle\Admin\Block\FacebookBlockService
        arguments:
            - "@twig.loader"
            - "@live.broadcast.facebook_api.service"
            - "@sonata.admin.channel"
        tags:
            - { name: sonata.block }
